/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.38
</auto-generated>
------------------------------------------------------------------------------ */

using ListWidget.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace ListWidget.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "SpaceXData_MVC", Title = "SpaceXData", SectionName = "CustomWidgets")]
	public class SpaceXDataController : Controller, IPersonalizable
	{
		// GET: SpaceXData
		public ActionResult Index()
		{
			var model = new SpaceXDataModel();
			model.Message = this.Message;
			return View(model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}