/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.38
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace ListWidget.Mvc.Models
{
	public class SpaceXDataModel
	{
		public string Message { get; set; }
	}
}